/**
 * Aurora Controller
 *
 * Provides functions for controlling the Live2D model based on instructions
 * generated by the Aurora engine. Handles character motions and facial expressions.
 */
import type { Live2DModel } from "pixi-live2d-display";
import type { AuroraInstruction } from "@/models/AuroraProps/AuroraInstructionProps";
import type { MutableRefObject } from "react";

/**
 * Appears an emotional instruction to the loaded Live2D model.
 * Triggers the appropriate motion animation and expressions.
 *
 * @param {MutableRefObject<Live2DModel | null>} modelRef - React ref containing the Live2D model instance
 * @param {AuroraInstruction} instruction - Instruction containing motion and expression names
 */
export function applyAuroraInstruction(
  modelRef: MutableRefObject<Live2DModel | null>,
  instruction: AuroraInstruction
) {
  if (!modelRef.current) {
    console.warn("⚠️ No Live2D model loaded to apply instruction.");
    return;
  }

  const { motion, expression } = instruction;

  console.log("🎭 Applying instruction:", instruction);

  try {
    // Play motion/animation if available
    if (motion) {
      // We accept both base names (haru_g_m01) and full paths (/models/..../haru_g_m01.motion3.json)
      const isPath = motion.includes("/") || motion.toLowerCase().endsWith(".json");
      const motionUrl = isPath ? motion : `/models/haru/runtime/motion/${motion}.motion3.json`;
      console.log("▶️ Executing motion (url):", motionUrl);
      try {
        // Prefer using motionManager to play animation by URL
        const mm: any = modelRef.current.internalModel?.motionManager;
        mm?.stopAllMotions?.();
        if (typeof mm?.startMotion === "function") {
          mm.startMotion(motionUrl, 0, 1);
        } else if (typeof (modelRef.current as any).motion === "function") {
          // Fallback to convenience API
          const motionName = motionUrl
            .replace(/\.motion3\.json$/i, "")
            .split("/")
            .pop();
          (modelRef.current as any).motion(motionName);
        }
      } catch (e) {
        console.warn(
          "⚠️ Could not play motion with motionManager, trying fallback:",
          e
        );
        try {
          const motionName = motion.replace(/\.motion3\.json$/i, "");
          (modelRef.current as any).motion(motionName);
        } catch (ee) {
          console.error("❌ Error playing motion (fallback):", ee);
        }
      }
    }

    // Change expression if supported by model
    if (expression) {
      try {
        const em = (modelRef.current.internalModel as any)?.expressionManager;
        if (em && typeof em.setExpression === "function") {
          const expUrl = `/models/haru/runtime/expressions/${expression}.exp3.json`;
          em.setExpression(expUrl).catch?.(() =>
            console.warn("⚠️ Expression not found:", expression)
          );
        } else {
          // No expressionManager available: caller should use params or motions as fallback
          console.debug(
            "ℹ️ expressionManager not available — use params or motions for expressions."
          );
        }
      } catch (err) {
        console.warn("⚠️ Error applying expression:", err);
      }
    }
  } catch (err) {
    console.error("❌ Error applying Aurora instruction:", err);
  }
}
