/**
 * Aurora Avatar Instruction Model
 *
 * Instructions for controlling the Aurora Live2D avatar's emotional expression,
 * facial expression, and motion animation. Generated by the ANA (emotional analysis)
 * module based on chat response content.
 */

/**
 * AuroraInstruction - Avatar animation and expression state
 *
 * Complete instruction set for controlling the avatar's visual representation.
 * Includes emotional state, facial expression, body motion, and optional response text.
 *
 * Generated by AnaCore.processUserMessage() after analyzing the chat response text
 * for emotional keywords. Used by AuroraController to apply animations to Live2D model.
 *
 * @interface AuroraInstruction
 * @property {string} emotion - Emotional state (happy, sad, angry, neutral, etc.)
 * @property {string} expression - Facial expression name (smile, frown, surprise, etc.)
 * @property {string} motion - Animation motion file name/ID (haru_g_m01, haru_g_idle, etc.)
 * @property {string} [text] - Optional chat response text to display
 *
 * @example
 * const happyInstruction: AuroraInstruction = {
 *   emotion: "happy",
 *   expression: "smile",
 *   motion: "haru_g_m02",
 *   text: "That's wonderful news!"
 * }
 *
 * const sadInstruction: AuroraInstruction = {
 *   emotion: "sad",
 *   expression: "frown",
 *   motion: "haru_g_idle",
 *   text: "I'm sorry to hear that..."
 * }
 */
export interface AuroraAction {
  type: "NAVIGATE" | "SCROLL" | "HIGHLIGHT" | "OPEN_CHAT" | "CLOSE_CHAT" | "SEARCH" | "ACCESS" | "EXPLAIN";
  target: string;
}

export interface AuroraInstruction {
  emotion: string;
  expression: string;
  motion: string;
  text?: string;
  action?: AuroraAction;
}
